# Use the official Loki image as the base
FROM grafana/loki:latest

# Copy your loki-config.yaml into the container
COPY loki-config.yaml /etc/loki/loki-config.yaml

# Specify the command to run Loki with the custom configuration and additional flag
ENTRYPOINT ["/usr/bin/loki", "-config.file=/etc/loki/loki-config.yaml", "-validation.allow-structured-metadata=false"]