# Start from the official Grafana image
FROM grafana/grafana:latest

# Set the working directory to root
WORKDIR /

# Copy the Grafana configuration file into the provisioning directory
COPY grafana-datasources.yaml /etc/grafana/provisioning/datasources/

# Switch back to the Grafana user
USER grafana

# Run Grafana (default entrypoint)
CMD ["/run.sh"]
