server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml # Path to store the positions file for tracking log positions

clients:
  - url: https://loki.tldrlw.com/loki/api/v1/push # Your Loki endpoint

scrape_configs:
  - job_name: cloudwatch
    aws_sd_configs:
      - region: "us-east-1" # Your AWS region

    cloudwatch:
      log_group_names:
        - "/aws/lambda/monza-tldrlw-constructors-update"
        - "/aws/lambda/monza-tldrlw-drivers-update"
        - "/aws/lambda/monza-tldrlw-get"
        - "/aws/lambda/monza-tldrlw-get-constructors"
        - "/aws/lambda/monza-tldrlw-get-drivers"
        - "/aws/lambda/monza-tldrlw-get-results"
        - "/aws/lambda/monza-tldrlw-post"
        - "/aws/lambda/monza-tldrlw-post-image"
        - "/aws/lambda/monza-tldrlw-post-result"
        - "/aws/lambda/monza-tldrlw-standings-compute"
      region: "us-east-1" # Your AWS region

    # No pipeline_stages: Collects everything logged
    relabel_configs:
      - source_labels: [__meta_aws_cloudwatch_log_group]
        target_label: log_group
      - source_labels: [__meta_aws_cloudwatch_log_stream]
        target_label: log_stream
